---
abstract: 'DWIM code blocks for smart matching'
author:
  - 'Rodrigo de Oliveira <rodrigolive@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Go
requires:
  Carp: 0
  Exporter::Tidy: 0
  PadWalker: 0
  Scalar::Util: 0
  overload: 0
  perl: v5.10
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Sub-Go
  homepage: http://search.cpan.org/perldoc?Sub-Go
  repository: git://github.com/rodrigolive/sub-go.git
version: 0.01
